/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as RequestsIdIndexRouteImport } from './routes/requests.$id.index'
import { Route as RequestsIdEditRouteImport } from './routes/requests.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdIndexRoute = RequestsIdIndexRouteImport.update({
  id: '/requests/$id/',
  path: '/requests/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdEditRoute = RequestsIdEditRouteImport.update({
  id: '/requests/$id/edit',
  path: '/requests/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/vendors': typeof VendorsRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/vendors': typeof VendorsRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/requests/$id': typeof RequestsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/vendors': typeof VendorsRoute
  '/requests/$id/edit': typeof RequestsIdEditRoute
  '/requests/$id/': typeof RequestsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/vendors' | '/requests/$id/edit' | '/requests/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/vendors' | '/requests/$id/edit' | '/requests/$id'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/vendors'
    | '/requests/$id/edit'
    | '/requests/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  VendorsRoute: typeof VendorsRoute
  RequestsIdEditRoute: typeof RequestsIdEditRoute
  RequestsIdIndexRoute: typeof RequestsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/': {
      id: '/requests/$id/'
      path: '/requests/$id'
      fullPath: '/requests/$id/'
      preLoaderRoute: typeof RequestsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id/edit': {
      id: '/requests/$id/edit'
      path: '/requests/$id/edit'
      fullPath: '/requests/$id/edit'
      preLoaderRoute: typeof RequestsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  VendorsRoute: VendorsRoute,
  RequestsIdEditRoute: RequestsIdEditRoute,
  RequestsIdIndexRoute: RequestsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
